site_name: Simple Piracy Guide
copyright: Â© Eason Li 2024 https://eason.cloud Made With â¤ï¸ ğŸ= Recommended

site_author: Eason Li

site_description: Simple Piracy Guide For Noobs

theme:
  name: material  
  favicon: 
  icon:
    logo: material/pirate
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/toggle-switch-off
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to system preference

nav:
- ğŸ´â€â˜ ï¸Getting Started: 'index.md'
- âš ï¸Safety Precautions: 'safety-precautions.md'
- ğŸ§¾Guide And Tools: 'guides.md'
- ğŸ“ºMovies/Anime /TV Shows: 'movies-anime-tv.md'
- ğŸ“–Educational Resources: 'educational-resources.md'
- ğŸ®Games: 'games.md'
